name: anime_watchlist
description: "Anime Watchlist - Track your anime library"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1
  dio: ^5.9.2
  graphql_flutter: ^5.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  uuid: ^4.5.3
  intl: ^0.20.2
  share_plus: ^10.1.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3
  drift_dev: ^2.22.1

flutter:
  uses-material-design: true
